version: 2
updates:
  # Website npm dependencies
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 5
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      security-updates:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "website"
    commit-message:
      prefix: "chore(deps)"

  # Android Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 5
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      security-updates:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "android"
    commit-message:
      prefix: "chore(deps)"

  # iOS Swift Package Manager dependencies
  - package-ecosystem: "swift"
    directory: "/ios"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 5
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      security-updates:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "ios"
    commit-message:
      prefix: "chore(deps)"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 3
    groups:
      security-updates:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(ci)"
