[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/?privacy"
  to = "/privacy"
  status = 301

[[redirects]]
  from = "/?tos"
  to = "/terms"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
