name: Android CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'android/**'
      - '.github/workflows/ci-android.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'android/**'
      - '.github/workflows/ci-android.yml'

jobs:
  build-and-test:
    name: Build and Test Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Check Kotlin code style
        run: |
          cd android
          ./gradlew ktlintCheck

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Run Unit Tests
        run: |
          cd android
          ./gradlew testDebugUnitTest

      - name: Generate JaCoCo Test Report
        run: |
          cd android
          ./gradlew jacocoDebugTestReport

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: android/app/build/test-results/

      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: android/app/build/reports/jacoco/

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: android/app/build/outputs/apk/debug/*.apk

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'SmilePile-Android'
          path: 'android/'
          format: 'HTML'
          args: >
            --enableRetired
            --enableExperimental

      - name: Upload security scan results
        uses: actions/upload-artifact@v3
        with:
          name: security-scan-results
          path: reports/